cat("Project packages loading")
library(tidyverse)
library(reshape2)
library(xlsx)
library(parallel)
library(foreach)
library(doParallel)
library(data.table)
library(rstan)
library(rstanarm)
library(rstantools)
library(arm)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')

