cat("Project packages loading")
library(tidyverse)
library(foreach)
library(parallel)
library(doParallel)
library(arm)
library(lme4)
library(rstanarm)
library(rstan)
library(rstantools)
library(reshape2)
library(gridExtra)
library(matrixStats)
library(Hmisc)
library(xlsx)
library(readxl)
library(gt)
library(ggpubr)
library(rio)
library(foreign)
library(brms)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
